CONFIG_TEST_FORCE_STORAGE_PARTITION=y
CONFIG_USE_DT_CODE_PARTITION=y
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_IMGTOOL_SIGN_VERSION="0.0.0+0"
CONFIG_MCUBOOT_IMGTOOL_OVERWRITE_ONLY=y
CONFIG_MCUBOOT_GENERATE_UNSIGNED_IMAGE=y
CONFIG_MCUBOOT_BOOTLOADER_MODE_OVERWRITE_ONLY=y
CONFIG_TEST_DRIVER_FLASH_SIZE=16777216
